# Generated by Django 5.2.6 on 2026-09-01 15:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('alert_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], default='INFO', max_length=20)),
                ('flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=100, unique=True)),
                ('location_name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crop_image_path', models.CharField(blank=True, max_length=512)),
                ('speed_estimate', models.FloatField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_logs', to='anpr_engine.cameranode')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['license_plate', 'captured_at'], name='detection_plate_capture_idx')],
            },
        ),
    ]
