# Generated by Django 5.2.17 on 2026-09-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anpr_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlog',
            name='frame_timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CameraVideoFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='video_feeds/')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_feeds', to='anpr_engine.cameranode')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='video_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='anpr_engine.cameravideofeed'),
        ),
    ]
